version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: flask-backend
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: routine-worker
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - redis
    command: ["python", "main.py"]
    environment:
      - REDIS_HOST=redis

  otp:
    image: openjdk:17-jdk-slim
    container_name: otp-server
    working_dir: /otp
    volumes:
      - ./otp:/otp
    command: ["java", "-jar", "otp-server.jar"]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    network_mode: host